server:
  port: 8002
spring:
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
    datasource:
      # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
      driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
      # ShardingSphere 配置文件路径
      url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
    data:
      redis:
        host: localhost
        port: 6379
        password: redis
    config:
      import: classpath:sa-token.yaml