server:
  port: 8001
spring:
    datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
      driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
      url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
    data:
      redis:
        host: 127.0.0.1
        port: 6379
        password: redis
    mvc:
      view:
        prefix: /templates/
        suffix: .html
shortLink:
  stats:
    locale:
      amap-key: 36303cbd115d7a707c6ae0de689035db
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
